/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistasGestionPedidos;

import clases.Envio;
import clases.Pago;
import clases.Pedido;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class vistaGestionPedidos extends javax.swing.JFrame {

    LinkedList<Pedido> pedidoList = new LinkedList<>();
    LinkedList<Pago> pagoList = new LinkedList<>();
    LinkedList<Envio> envioLista = new LinkedList<>();

    /**
     * Creates new form vistaGestionPedidos
     */
    public vistaGestionPedidos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idPedido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fecRealizaPed = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nomProValor = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        canProdPedido = new javax.swing.JTextField();
        estadoPedido = new javax.swing.JCheckBox();
        crearPedido = new javax.swing.JButton();
        editarPedido = new javax.swing.JButton();
        buscarPedido = new javax.swing.JButton();
        eliminarPedido = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        idPedidoPago = new javax.swing.JTextField();
        buscarPedPago = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        idPago = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        fechaPago = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        medioPago = new javax.swing.JComboBox<>();
        aceptarPago = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        idPagoEnvio = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        IdEnvio = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        fecEnvio = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        dirEnvio = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        compañiaTransEnv = new javax.swing.JComboBox<>();
        finalizadoEnvio = new javax.swing.JCheckBox();
        crearEnvio = new javax.swing.JButton();
        eliminarEnvio = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPaso1 = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaPagos = new javax.swing.JList<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        envioList = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTabbedPane1.setForeground(new java.awt.Color(153, 0, 0));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Manegador de Pedidos ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("ID Pedido");

        idPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPedidoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Fecha Realizado");

        fecRealizaPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecRealizaPedActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Producto - valor ");

        nomProValor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "* Arroz  Valor Uni $ 1.800", "* Pasta  Valor Uni $ 2.200", "* Panela Valor Uni $ 1.300" }));
        nomProValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomProValorActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Cantidad");

        canProdPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canProdPedidoActionPerformed(evt);
            }
        });

        estadoPedido.setText("Creado");

        crearPedido.setText("Crear");
        crearPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearPedidoActionPerformed(evt);
            }
        });

        editarPedido.setText("Editar ");
        editarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarPedidoActionPerformed(evt);
            }
        });

        buscarPedido.setText("Buscar");
        buscarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPedidoActionPerformed(evt);
            }
        });

        eliminarPedido.setText("Eliminar");
        eliminarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(117, 117, 117)
                            .addComponent(idPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(104, 104, 104)
                            .addComponent(jLabel4)
                            .addGap(46, 46, 46)
                            .addComponent(fecRealizaPed, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(155, 155, 155)
                            .addComponent(estadoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(crearPedido)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nomProValor, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 2, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(canProdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(editarPedido)
                                        .addGap(64, 64, 64)
                                        .addComponent(buscarPedido)
                                        .addGap(71, 71, 71)
                                        .addComponent(eliminarPedido)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecRealizaPed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomProValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(estadoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(canProdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearPedido)
                    .addComponent(editarPedido)
                    .addComponent(buscarPedido)
                    .addComponent(eliminarPedido))
                .addGap(82, 82, 82))
        );

        jTabbedPane1.addTab("paso 1", jPanel1);

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("TRANSACION DE PAGO");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("1.   Id Pedido");

        idPedidoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPedidoPagoActionPerformed(evt);
            }
        });

        buscarPedPago.setText("Buscar Pedido");
        buscarPedPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPedPagoActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("2.    Id Pago");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Fecha De Pago");

        fechaPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaPagoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Medio De pago");

        medioPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EFECTIVO", "TARJETA CREDITO", "TARJETA DEBITO", "NEQUI", "DAVIPLATA" }));

        aceptarPago.setText("Aceptar  Pago");
        aceptarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarPagoActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel18.setText("Nota: puede validar si existe pedido");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(232, 232, 232)
                                .addComponent(buscarPedPago, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idPedidoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fechaPago)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(idPago, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel13)
                .addGap(29, 29, 29)
                .addComponent(medioPago, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(aceptarPago)
                .addGap(82, 82, 82))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idPedidoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarPedPago, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medioPago, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aceptarPago))
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(110, 110, 110))
        );

        jTabbedPane1.addTab("paso 2", jPanel2);

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("TRANSACION DE ENVIOS");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Recordatorio:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel17.setText(" para Enviar se requiere haber realizado pedido y su pago");
        jLabel17.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel17KeyPressed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("ID pago");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("ID Envio");

        IdEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdEnvioActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Fecha envio");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Dirrecion Envio ");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Compañia Trans.");

        compañiaTransEnv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Servientrega", "Interrapidisimo", "Envia" }));

        finalizadoEnvio.setText("Fianlizado");
        finalizadoEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizadoEnvioActionPerformed(evt);
            }
        });

        crearEnvio.setText("Crear envio");
        crearEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearEnvioActionPerformed(evt);
            }
        });

        eliminarEnvio.setText("Eliminar envio");
        eliminarEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarEnvioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 56, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel19))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(fecEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(idPagoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dirEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabel20))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(compañiaTransEnv, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(finalizadoEnvio)
                            .addComponent(IdEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(crearEnvio)
                .addGap(112, 112, 112)
                .addComponent(eliminarEnvio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(IdEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idPagoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecEnvio, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dirEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(compañiaTransEnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finalizadoEnvio))
                .addGap(67, 67, 67)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearEnvio)
                    .addComponent(eliminarEnvio))
                .addGap(41, 41, 41))
        );

        jTabbedPane1.addTab("paso 3", jPanel3);

        listPaso1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Pedido numero 1", "Pedido numero 2", "Pedido numero 3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listPaso1);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Paso 1: lista Pedidos");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Resumen De las Actualizaciones");

        listaPagos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Registro pago 1", "Registro pago 2", "Registro pago 3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaPagos);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Paso 2: lista Pagos");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("Paso 3: lista Envios");

        envioList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Registro envio 1", "Registro envio 2", "Registro envio 3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(envioList);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("General", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("", jPanel5);

        jLabel15.setBackground(new java.awt.Color(102, 153, 255));
        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 102));
        jLabel15.setText("ADMINISTRACION DE PEDIDOS, PAGOS Y ENVIOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearPedidoActionPerformed

        try {
            String idPedi = idPedido.getText();
            String fechRealizacion = fecRealizaPed.getText();
            String nomProdValorUni = nomProValor.getSelectedItem().toString();
            boolean estado = estadoPedido.isSelected();
            int cantidad = Integer.parseInt(canProdPedido.getText());
            int total = 0;

            if (nomProdValorUni.equals("* Arroz  Valor Uni $ 1.800")) {
                total = cantidad * 1800;
            }
            if (nomProdValorUni.equals("* Pasta  Valor Uni $ 2.200")) {
                total = cantidad * 2200;
            }
            if (nomProdValorUni.equals("* Panela Valor Uni $ 1.300")) {
                total = cantidad * 1300;
            }

            if (idPedi.equals("") || fechRealizacion.equals("")) {
                JOptionPane.showMessageDialog(this, "Existen Datos Vacios");
            } else {
                Pedido pedido = new Pedido(idPedi, fechRealizacion, estado, total, nomProdValorUni, cantidad);
                pedidoList.add(pedido);
                cicloLista();
                JOptionPane.showMessageDialog(this, "Creacion exitosa");
                clearCampos();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Falta cantidad de los productos");
        }

    }//GEN-LAST:event_crearPedidoActionPerformed

    private void canProdPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canProdPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_canProdPedidoActionPerformed

    private void nomProValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomProValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomProValorActionPerformed

    private void fecRealizaPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecRealizaPedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fecRealizaPedActionPerformed

    private void idPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPedidoActionPerformed

    private void eliminarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarPedidoActionPerformed

        String idPed = idPedido.getText();
        boolean opc = false;

        for (Pedido pedido : pedidoList) {
            if (pedido.getIdPedido().equals(idPed)) {
                pedidoList.remove(pedido);
                clearCampos();
                cicloLista();
                JOptionPane.showMessageDialog(this, "Elimancion Exitosa del Id " + pedido.getIdPedido());
                opc = true;
                break;
            }

        }
        if (!opc) {
            JOptionPane.showMessageDialog(this, "el id  " + idPed + " del pedido no existe");
        }
    }//GEN-LAST:event_eliminarPedidoActionPerformed

    private void editarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarPedidoActionPerformed

        String idPed = idPedido.getText();
        boolean opc = false;

        for (Pedido pedido : pedidoList) {
            if (pedido.getIdPedido().equals(idPed)) {
                String fecRealiPed = fecRealizaPed.getText();
                String nomProdValorUni = nomProValor.getSelectedItem().toString();
                int canProPedido = Integer.parseInt(canProdPedido.getText());
                boolean estadoPedi = estadoPedido.isSelected();

                pedido.setCantidad(canProPedido);
                pedido.setFechRealizacion(fecRealiPed);
                pedido.setNomProdValorUni(nomProdValorUni);
                pedido.setEstado(estadoPedi);

                cicloLista();
                JOptionPane.showMessageDialog(this, "Datos Actaulizados");
                opc = true;
                break;
            }
        }
        if (!opc) {
            JOptionPane.showMessageDialog(this, " No encontrado el id pedido " + idPed);
            clearCampos();

        }
    }//GEN-LAST:event_editarPedidoActionPerformed

    private void buscarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPedidoActionPerformed

        String idped = idPedido.getText();
        boolean opc = false;

        for (Pedido pedido : pedidoList) {
            if (pedido.getIdPedido().equals(idped)) {
                fecRealizaPed.setText(pedido.getFechRealizacion());
                estadoPedido.setSelected(pedido.getEstado());
                nomProValor.setSelectedItem(pedido.getNomProdValorUni());
                canProdPedido.setText(pedido.getCantidad() + "");

                JOptionPane.showMessageDialog(this, " Datos encontrados");
                opc = true;
                break;
            }
        }
        if (!opc) {
            JOptionPane.showMessageDialog(this, "El id " + idped + " no fue encontrado");
            clearCampos();
        }
    }//GEN-LAST:event_buscarPedidoActionPerformed

    private void buscarPedPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPedPagoActionPerformed

        String idBuscarPedido = idPedidoPago.getText();
        boolean flag = false;

        for (Pedido pedido : pedidoList) {
            if (pedido.getIdPedido().equals(idBuscarPedido)) {
                JOptionPane.showMessageDialog(this, "Id encontrado puede continuar");
                flag = true;
            }

        }
        if (!flag) {

            JOptionPane.showMessageDialog(this, "Id " + idBuscarPedido + " no encontrado");
        }

    }//GEN-LAST:event_buscarPedPagoActionPerformed

    private void idPedidoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPedidoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPedidoPagoActionPerformed

    private void fechaPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaPagoActionPerformed

    private void aceptarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarPagoActionPerformed

        try {
            String idBuscarPed = idPedidoPago.getText();
            String idpag = idPago.getText();
            String fecPag = fechaPago.getText();
            String medioPagoo = medioPago.getSelectedItem().toString();

            if (idBuscarPed.equals("") || idpag.equals("") || fecPag.equals("")) {
                JOptionPane.showMessageDialog(this, "Hay campos vacios");
            } else {
                boolean flag = false;
                for (Pedido pedido : pedidoList) {
                    if (pedido.getIdPedido().equals(idBuscarPed)) {
                        Pago pago = new Pago(idpag, fecPag, medioPagoo, idBuscarPed, pedido);
                        pagoList.add(pago);
                        cicloPagos();
                        JOptionPane.showMessageDialog(this, "creacion exitosa");
                        clearCampos();
                        flag = true;
                        break;
                    }
                }
                if (!flag) {
                    JOptionPane.showMessageDialog(this, "no existe pedido registrado no se puede continuar ");

                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Hay campos vacios.....................");
        }
    }//GEN-LAST:event_aceptarPagoActionPerformed

    private void IdEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdEnvioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdEnvioActionPerformed

    private void finalizadoEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizadoEnvioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finalizadoEnvioActionPerformed

    private void crearEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearEnvioActionPerformed

        try {
            String idEnvioo = IdEnvio.getText();
            String idPagoEnv = idPagoEnvio.getText();
            String fecEnvi = fecEnvio.getText();
            String idDirEnvio = dirEnvio.getText();
            String companiaTrans = compañiaTransEnv.getSelectedItem().toString();
            boolean finalizaEnvio = finalizadoEnvio.isSelected();

            if (idPagoEnv.equals("") || idEnvioo.equals("") || fecEnvi.equals("") || idDirEnvio.equals("")) {
                JOptionPane.showMessageDialog(this, "Existen campos en blanco");
            } else {
                boolean flag = false;
                for (Pago pago : pagoList) {

                    if (pago.getIdPago().equals(idPagoEnv)) {
                        Envio envio = new Envio(idEnvioo, idPagoEnv, idDirEnvio, finalizaEnvio, fecEnvi, companiaTrans, pago);
                        envioLista.add(envio);
                        cicloEnvio();
                        JOptionPane.showMessageDialog(this, "Creacion exitosa de envio. valide su envio en la pestaña General");
                        clearCampos();
                        flag = true;
                        break;
                    }

                }
                if (!flag) {

                    JOptionPane.showMessageDialog(this, "No esta registrado el pago con el Id  " + idPagoEnv);
                    clearCampos();
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "falta algun campo ");
        }
    }//GEN-LAST:event_crearEnvioActionPerformed

    public void cicloEnvio() {
        DefaultListModel model = new DefaultListModel();
        for (Envio envio : envioLista) {
            int index = 0;
            String mensajeFinalizado;
            if (envio.getFinalizado() == false) {
                mensajeFinalizado = " no esta finalizado";
            } else {
                mensajeFinalizado = " esta finalizado";
            }
            String data = "ID " + envio.getIdEnvio() + " se enviara por la transportadora " + envio.getCompania() + " y su estado es " + mensajeFinalizado;
            model.add(index, data);
            index++;
        }
        envioList.setModel(model);

    }
    private void jLabel17KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel17KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17KeyPressed

    private void eliminarEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarEnvioActionPerformed
                     
        String idEnv = IdEnvio.getText();
        boolean flag = false;

        for (Envio envio : envioLista) {
            if (envio.getIdEnvio().equals(idEnv)) {
                envioLista.remove(envio);
                cicloEnvio();
                JOptionPane.showMessageDialog(this, " Eliminacion exitosa");
                clearCampos();
                flag = true;
                break;
            }
        }
        if (!flag) {
            JOptionPane.showMessageDialog(this, "Registro no encontrado el id pedido "+ idEnv);
            clearCampos();
        }
    }//GEN-LAST:event_eliminarEnvioActionPerformed

    public void cicloPagos() {
        DefaultListModel model = new DefaultListModel();
        for (Pago pago : pagoList) {
            int index = 0;
            String data = "Id " + pago.getIdPago() + " el medio de pago es " + pago.getMedioago() + " y que esta relacionado con el pedido " + pago.getIdPedido();
            model.add(index, data);
            index++;
        }
        listaPagos.setModel(model);

    }

    /*public Pedido retornarPedidoBusc(String idPedido){
        Pedido pedidoEncotrado = new Pedido(idPedido, idPedido, rootPaneCheckingEnabled, NORMAL, idPedido, WIDTH);
        for(Pedido pedido: pedidoList){
            if(pedido.getIdPedido().equals(idPedido)){
                return pedidoEncotrado;
            }
        }
        
    }*/
    public void cicloLista() {
        DefaultListModel model = new DefaultListModel();
        for (Pedido pedido : pedidoList) {
            int index = 0;
            String data = "ID " + pedido.getIdPedido() + " - " + pedido.getNomProdValorUni() + " su total es " + pedido.getTotal();
            model.add(index, data);
            index++;

        }
        listPaso1.setModel(model);
    }

    public void clearCampos() {
        idPedido.setText("");
        nomProValor.setSelectedIndex(0);
        canProdPedido.setText("");
        fecRealizaPed.setText("");
        estadoPedido.setSelected(false);

        idPedidoPago.setText("");
        idPago.setText("");
        medioPago.setSelectedItem(0);
        fechaPago.setText("");

        IdEnvio.setText("");
        idPagoEnvio.setText("");
        dirEnvio.setText("");
        fecEnvio.setText("");
        compañiaTransEnv.setSelectedIndex(0);
        finalizadoEnvio.setSelected(false);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaGestionPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaGestionPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaGestionPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaGestionPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaGestionPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IdEnvio;
    private javax.swing.JButton aceptarPago;
    private javax.swing.JButton buscarPedPago;
    private javax.swing.JButton buscarPedido;
    private javax.swing.JTextField canProdPedido;
    private javax.swing.JComboBox<String> compañiaTransEnv;
    private javax.swing.JButton crearEnvio;
    private javax.swing.JButton crearPedido;
    private javax.swing.JTextField dirEnvio;
    private javax.swing.JButton editarPedido;
    private javax.swing.JButton eliminarEnvio;
    private javax.swing.JButton eliminarPedido;
    private javax.swing.JList<String> envioList;
    private javax.swing.JCheckBox estadoPedido;
    private javax.swing.JTextField fecEnvio;
    private javax.swing.JTextField fecRealizaPed;
    private javax.swing.JTextField fechaPago;
    private javax.swing.JCheckBox finalizadoEnvio;
    private javax.swing.JTextField idPago;
    private javax.swing.JTextField idPagoEnvio;
    private javax.swing.JTextField idPedido;
    private javax.swing.JTextField idPedidoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> listPaso1;
    private javax.swing.JList<String> listaPagos;
    private javax.swing.JComboBox<String> medioPago;
    private javax.swing.JComboBox<String> nomProValor;
    // End of variables declaration//GEN-END:variables
}
