/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;
import javax.swing.JOptionPane;
import ClasesMascotas.*;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import controlador.*;
/**
 *
 * @author Esquivel_Cesar
 */
public class vsitamascotas extends javax.swing.JFrame {
    ctrolmascota ctlmascota;
    LinkedList<mascota> dogObjectList = new LinkedList<>();
    /**
     * Creates new form vsitamascotas
     */
    public vsitamascotas() {
        initComponents();
        this.ctlmascota = new ctrolmascota();
        this.dogObjectList = ctlmascota.ListarMascota("Perro");
        this.listasmascotas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        list = new javax.swing.JTabbedPane();
        listasmascotas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listpet = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtcodperro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnomperro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtanioperro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcolorperro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comesaludperro = new javax.swing.JComboBox<>();
        comrazaperro = new javax.swing.JComboBox<>();
        btncrearperro = new javax.swing.JButton();
        btnbuscarperro = new javax.swing.JButton();
        btneditarperro = new javax.swing.JButton();
        btneliminarperro = new javax.swing.JButton();
        checpedperro = new javax.swing.JCheckBox();
        limpiar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtidperro = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtidmascota = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("ADMINISTRACION MASCOTAS");

        listpet.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Código     Nombre     Raza         Color" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listpet);

        jLabel8.setText("Código");

        jLabel9.setText("Nombre");

        jLabel10.setText("Raza");

        jLabel11.setText("Color");

        javax.swing.GroupLayout listasmascotasLayout = new javax.swing.GroupLayout(listasmascotas);
        listasmascotas.setLayout(listasmascotasLayout);
        listasmascotasLayout.setHorizontalGroup(
            listasmascotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listasmascotasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listasmascotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                    .addGroup(listasmascotasLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel8)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel9)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel10)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        listasmascotasLayout.setVerticalGroup(
            listasmascotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listasmascotasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listasmascotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        list.addTab("Listas", listasmascotas);

        jLabel2.setText("Codigo");

        jLabel3.setText("Nombre");

        jLabel4.setText("Año Nac");

        jLabel5.setText("Color");

        txtcolorperro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcolorperroActionPerformed(evt);
            }
        });

        jLabel6.setText("Estado Salud");

        jLabel7.setText("Raza");

        comesaludperro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saludable", "Enfermo" }));
        comesaludperro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comesaludperroActionPerformed(evt);
            }
        });

        comrazaperro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beagle", "Jack Russell", "Pastor Alemán", "Fox Terrier Toy", "Yorkshire Terrier", "Chihuahua", "Pastor Alemán" }));

        btncrearperro.setText("Crear");
        btncrearperro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearperroActionPerformed(evt);
            }
        });

        btnbuscarperro.setText("Buscar");
        btnbuscarperro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarperroActionPerformed(evt);
            }
        });

        btneditarperro.setText("Editar");
        btneditarperro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarperroActionPerformed(evt);
            }
        });

        btneliminarperro.setText("Eliminar");
        btneliminarperro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarperroActionPerformed(evt);
            }
        });

        checpedperro.setText("Pedigree");
        checpedperro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checpedperroActionPerformed(evt);
            }
        });

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        jLabel12.setText("Id Perro");

        txtidperro.setEditable(false);

        jLabel13.setText("Id Mascota");

        txtidmascota.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtcodperro, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(txtanioperro)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comesaludperro, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addGap(32, 32, 32)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnomperro)
                            .addComponent(txtcolorperro, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comrazaperro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addComponent(checpedperro))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(btncrearperro)
                                .addGap(18, 18, 18)
                                .addComponent(btnbuscarperro))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtidperro, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtidmascota))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btneditarperro)
                                .addGap(18, 18, 18)
                                .addComponent(btneliminarperro)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(limpiar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcodperro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtnomperro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtanioperro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtcolorperro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(comesaludperro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comrazaperro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checpedperro))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtidperro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtidmascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncrearperro)
                    .addComponent(btnbuscarperro)
                    .addComponent(btneditarperro)
                    .addComponent(btneliminarperro)
                    .addComponent(limpiar))
                .addContainerGap())
        );

        list.addTab("Admin Perro", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 239, Short.MAX_VALUE)
        );

        list.addTab("Admin Gato", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(list)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(341, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(46, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcolorperroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcolorperroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcolorperroActionPerformed

    private void comesaludperroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comesaludperroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comesaludperroActionPerformed

    private void btncrearperroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearperroActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(this, "Presiono el botón Crear");

        try {
            String codPerro = txtcodperro.getText();
            String nomPerro = txtnomperro.getText();
            String colPerro = txtcolorperro.getText();
            int nacPerro = Integer.parseInt(txtanioperro.getText());
            String saludPerro = comesaludperro.getSelectedItem().toString();
            String razaPerro = comrazaperro.getSelectedItem().toString();
            boolean pedigPerro = checpedperro.isSelected();

            if( codPerro.equals("") || nomPerro.equals("") || colPerro.equals("")){
                JOptionPane.showMessageDialog(this, "Existen Campos Vacios");
            }
            else{
                clsPerro perro = new clsPerro(0, razaPerro, pedigPerro, 0, codPerro, nomPerro, nacPerro, colPerro, saludPerro);
                ctlmascota.CrearMascota(perro);
                
                dogObjectList.add(perro);
                this.listasmascotas();
                JOptionPane.showMessageDialog(this, "Datos ingresados con Exito");
                this.borrarcampos();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor escrba la edad del perro");
        }

    }//GEN-LAST:event_btncrearperroActionPerformed

    private void btnbuscarperroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarperroActionPerformed
        // TODO add your handling code here:

        String codigo = txtcodperro.getText();
        clsPerro perro = (clsPerro) ctlmascota.BuscarMascota(codigo, "Perro");
        if (perro == null){
            JOptionPane.showMessageDialog(this, "Codigo no Existe");
        }
        else{
                txtidperro.setText(perro.getId()+ "");
                txtidmascota.setText(perro.getId()+ "");
                txtnomperro.setText(perro.getNombre());
                txtcolorperro.setText(perro.getColor());
                txtanioperro.setText(perro.getAnioNac()+ "");
                comesaludperro.setSelectedItem(perro.getEstadoSalud());
                comrazaperro.setSelectedItem(perro.getRaza());
                checpedperro.setSelected(perro.getPedigree());
        }
        
    }//GEN-LAST:event_btnbuscarperroActionPerformed

    private void btneditarperroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarperroActionPerformed
        // TODO add your handling code here:
      
                // recibimos los datos de los campos de texto
                String code = txtcodperro.getText();
                String nom = txtnomperro.getText();
                String col = txtcolorperro.getText();
                int nac = Integer.parseInt(txtanioperro.getText());
                String salud = comesaludperro.getSelectedItem().toString();
                String raza = comrazaperro.getSelectedItem().toString();
                boolean pedig = checpedperro.isSelected();
                
                //recibimos los id ya creados en los campos de texto en la vista
                // colocamos dentro de un try por si el usuario no digita ningun codigo le mostremos un msj de erro
                try{
                    int idperro = Integer.parseInt(txtidperro.getText());
                    int idmascota = Integer.parseInt(txtidmascota.getText());
                
                    //instanciamos el constructor
                    clsPerro perro = new clsPerro(idperro, raza, pedig, idmascota, code, nom, nac, col, salud);
                    
                    boolean respuesta = ctlmascota.EditarMascota(perro);
                    if (respuesta){
                        JOptionPane.showMessageDialog(this, "Edición Exitosa");
                        this.borrarcampos();
                    }
                    else{
                        
                        JOptionPane.showMessageDialog(this, "Error al actualizar");
                    }
                }
                catch (Exception e){
                    JOptionPane.showMessageDialog(this, "Busque un código para editarlo");
                }
    }//GEN-LAST:event_btneditarperroActionPerformed

    private void btneliminarperroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarperroActionPerformed
                String code = txtcodperro.getText();
                String nom = txtnomperro.getText();
                String col = txtcolorperro.getText();
                int nac = Integer.parseInt(txtanioperro.getText());
                String salud = comesaludperro.getSelectedItem().toString();
                String raza = comrazaperro.getSelectedItem().toString();
                boolean pedig = checpedperro.isSelected();
        
        
                try{
                    int idperro = Integer.parseInt(txtidperro.getText());
                    int idmascota = Integer.parseInt(txtidmascota.getText());
                    clsPerro perro = new clsPerro(idperro, raza, pedig, idmascota, code, nom, nac, col, salud);
                    boolean respuesta = ctlmascota.EliminarMascota(perro);
                    if (respuesta){
                        JOptionPane.showMessageDialog(this, "Registro Eliminado");
                        this.borrarcampos();
                    }
                    else{
                        
                        JOptionPane.showMessageDialog(this, "Error al Eliminar");
                    }
                }
                catch (Exception e){
                    JOptionPane.showMessageDialog(this, "Busque un código para Eliminar");
                }
       /* for (clsPerro perro : dogObjectList) {

           if (perro.getCodigo().equals(code)) {
                this.dogObjectList.remove(perro);
                this.borrarcampos();
                this.listasmascotas();
                JOptionPane.showMessageDialog(this, "Registro Borrado");
                opc = true;
                break;
            }
        }
        if (!opc) {
            JOptionPane.showMessageDialog(this, "Codigo no Existe");
        }        // TODO add your handling code here:*/
    }//GEN-LAST:event_btneliminarperroActionPerformed

    private void checpedperroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checpedperroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checpedperroActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
        this.borrarcampos();
    }//GEN-LAST:event_limpiarActionPerformed
 // MOSTRAR LOS REGISTROS EN LA OPCION LISTA
    
    private void listasmascotas() {
        DefaultListModel model = new DefaultListModel();
        int index = 0;
        for (mascota perro : dogObjectList){
            String data = perro.getCodigo() + "       -       " + perro.getNombre() + "       -     " + perro.getEstadoSalud()+ "       -      " + perro.getColor() + "     Tipo Perro";
            model.add(index, data);
            index++;
        }
        listpet.setModel(model);
        
    }   
    
    //metodo para borrar los campos
    
    private void borrarcampos(){
        
        
        txtcodperro.setText("");
        txtnomperro.setText("");
        txtcolorperro.setText("");
        txtanioperro.setText("");
        comesaludperro.setSelectedIndex(0);
        comrazaperro.setSelectedIndex(0);
        checpedperro.setSelected(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vsitamascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vsitamascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vsitamascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vsitamascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vsitamascotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscarperro;
    private javax.swing.JButton btncrearperro;
    private javax.swing.JButton btneditarperro;
    private javax.swing.JButton btneliminarperro;
    private javax.swing.JCheckBox checpedperro;
    private javax.swing.JComboBox<String> comesaludperro;
    private javax.swing.JComboBox<String> comrazaperro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiar;
    private javax.swing.JTabbedPane list;
    private javax.swing.JPanel listasmascotas;
    private javax.swing.JList<String> listpet;
    private javax.swing.JTextField txtanioperro;
    private javax.swing.JTextField txtcodperro;
    private javax.swing.JTextField txtcolorperro;
    private javax.swing.JTextField txtidmascota;
    private javax.swing.JTextField txtidperro;
    private javax.swing.JTextField txtnomperro;
    // End of variables declaration//GEN-END:variables
}
