/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import ClasesMascotas.Gato;
import ClasesMascotas.Mascota;
import ClasesMascotas.Pajaro;
import ClasesMascotas.Perro;
import java.awt.List;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class VistasMascotas extends javax.swing.JFrame {

    LinkedList<Perro> objList = new LinkedList<>();
    LinkedList<Gato> objListGato = new LinkedList<>();
    LinkedList<Pajaro> objeListPajaro = new LinkedList<>();

    /**
     * Creates new form VistasMascotas
     */
    public VistasMascotas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crearPerro = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listasMascotas = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaGatos = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaPajaros = new javax.swing.JList<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        codPerro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nomPerro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nacPerro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        colorPerro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        saludPerro = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        razaPerro = new javax.swing.JComboBox<>();
        peligriPerro = new javax.swing.JCheckBox();
        buscarPerro = new javax.swing.JButton();
        editarPerro = new javax.swing.JButton();
        eliminarPerro = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        codGato = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nomGato = new javax.swing.JTextField();
        texFieldGato = new javax.swing.JLabel();
        nacGato = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        colorGato = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        saludGato = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        razaGato = new javax.swing.JComboBox<>();
        crearGato = new javax.swing.JButton();
        buscarGato = new javax.swing.JButton();
        editarGato = new javax.swing.JButton();
        eliminarGato = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        codPajaro = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        nomPajaro = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        nacPajaro = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        colorPajaro = new javax.swing.JTextField();
        razPajaro = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        saludPajaro = new javax.swing.JComboBox<>();
        crearPajaro = new javax.swing.JButton();
        buscarPajaro = new javax.swing.JButton();
        editarPajaro = new javax.swing.JButton();
        eliminarPajaro = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        crearPerro.setText("Crear");
        crearPerro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearPerroActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        listasMascotas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1. Perro", "2. Perro", "3. Perro", "4. Peroo" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listasMascotas);

        listaGatos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1. Gato", "2. Gato", "3. Gato", "4. Gato" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaGatos);

        listaPajaros.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1.  Pajaro", "2 . Pajaro", "3.  Pajaro", "4.  Pajaro" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listaPajaros);

        jLabel19.setText("Lista Perros");

        jLabel20.setText("Lista Gatos");

        jLabel21.setText("Lista Pajaros");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel19)
                .addGap(81, 81, 81)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(87, 87, 87))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(jLabel21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listas Mascotas", jPanel1);

        jLabel1.setText("Codigo");

        codPerro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codPerroActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre Perro");

        jLabel3.setText("Año Nac");

        nacPerro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacPerroActionPerformed(evt);
            }
        });

        jLabel4.setText("Color");

        jLabel5.setText("Estado Salud");

        saludPerro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saludable", "Enfermo" }));

        jLabel6.setText("Raza");

        razaPerro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Criollo", "Pincher", "Pastor Alem" }));
        razaPerro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                razaPerroActionPerformed(evt);
            }
        });

        peligriPerro.setText("Peligri");
        peligriPerro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peligriPerroActionPerformed(evt);
            }
        });

        buscarPerro.setText("Buscar");
        buscarPerro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPerroActionPerformed(evt);
            }
        });

        editarPerro.setText("Editar");
        editarPerro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarPerroActionPerformed(evt);
            }
        });

        eliminarPerro.setText("Eliminar");
        eliminarPerro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarPerroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saludPerro, 0, 91, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nacPerro, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(codPerro))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(peligriPerro, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(buscarPerro)
                                .addGap(34, 34, 34)
                                .addComponent(editarPerro)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomPerro)
                    .addComponent(colorPerro)
                    .addComponent(razaPerro, 0, 130, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(eliminarPerro)
                .addGap(69, 69, 69))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(nomPerro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codPerro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(colorPerro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nacPerro))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(saludPerro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(razaPerro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(peligriPerro)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarPerro)
                    .addComponent(editarPerro)
                    .addComponent(eliminarPerro))
                .addGap(57, 57, 57))
        );

        jTabbedPane1.addTab("Admin Perros", jPanel2);

        jLabel8.setText("Codigo");

        jLabel9.setText("Nombre Gato");

        texFieldGato.setText("Año Nac");

        jLabel10.setText("Color");

        jLabel11.setText("Estado Salud");

        saludGato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saludable", "Enfermo" }));

        jLabel12.setText("Raza");

        razaGato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gato persa", "Gato bengala" }));

        crearGato.setText("Crear");
        crearGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearGatoActionPerformed(evt);
            }
        });

        buscarGato.setText("Buscar");
        buscarGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarGatoActionPerformed(evt);
            }
        });

        editarGato.setText("editar");
        editarGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarGatoActionPerformed(evt);
            }
        });

        eliminarGato.setText("Eliminar");
        eliminarGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarGatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(texFieldGato))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nacGato, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                            .addComponent(codGato)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(saludGato, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(editarGato))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(eliminarGato)
                                    .addComponent(razaGato, 0, 102, Short.MAX_VALUE)
                                    .addComponent(colorGato)
                                    .addComponent(nomGato)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(crearGato)
                        .addGap(31, 31, 31)
                        .addComponent(buscarGato)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nomGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texFieldGato)
                    .addComponent(nacGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(colorGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(saludGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(razaGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearGato)
                    .addComponent(buscarGato)
                    .addComponent(editarGato)
                    .addComponent(eliminarGato))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Admin Gatos", jPanel3);

        jLabel13.setText("Codigo");

        jLabel14.setText("Nombre Pajaro");

        jLabel15.setText("Año Nac");

        jLabel16.setText("Raza");

        jLabel17.setText("Color");

        razPajaro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Canarios", "Periquitos", "Cotorras" }));

        jLabel18.setText("Estado Salud");

        saludPajaro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saludable", "Enfermo" }));

        crearPajaro.setText("Crear");
        crearPajaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearPajaroActionPerformed(evt);
            }
        });

        buscarPajaro.setText("Buscar");

        editarPajaro.setText("Editar");

        eliminarPajaro.setText("Eliminar");
        eliminarPajaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarPajaroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(crearPajaro)
                        .addGap(28, 28, 28)
                        .addComponent(buscarPajaro)
                        .addGap(24, 24, 24)
                        .addComponent(editarPajaro))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nacPajaro)
                            .addComponent(codPajaro)
                            .addComponent(saludPajaro, 0, 82, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(razPajaro, 0, 110, Short.MAX_VALUE)
                            .addComponent(nomPajaro)
                            .addComponent(colorPajaro))
                        .addGap(57, 57, 57))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(eliminarPajaro)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(codPajaro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(nomPajaro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(nacPajaro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(colorPajaro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(razPajaro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(saludPajaro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearPajaro)
                    .addComponent(buscarPajaro)
                    .addComponent(editarPajaro)
                    .addComponent(eliminarPajaro))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Admin Pajaros", jPanel4);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("APLICACION DE ADMINISTRACION DE MASCOTAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codPerroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codPerroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codPerroActionPerformed

    private void razaPerroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_razaPerroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_razaPerroActionPerformed

    private void peligriPerroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peligriPerroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peligriPerroActionPerformed

    private void crearPerroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearPerroActionPerformed

        try {
            String codigo = codPerro.getText();
            String nombre = nomPerro.getText();
            String color = colorPerro.getText();
            int anhioNac = Integer.parseInt(nacPerro.getText());
            String raza = razaPerro.getSelectedItem().toString();
            String estadoSalud = saludPerro.getSelectedItem().toString();
            boolean peligri = peligriPerro.isSelected();

            if (codigo.equals("") || nombre.equals("") || color.equals("")) {
                JOptionPane.showMessageDialog(this, "existen datos vacios");
            } else {
                Perro perro1 = new Perro(raza, peligri, codigo, nombre, anhioNac, color, estadoSalud);
                objList.add(perro1);
                this.cicloLista();
                JOptionPane.showMessageDialog(this, "Creacion exitosa");
                this.clear();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Falta ingresar valor año de nacimiento");
        }

    }//GEN-LAST:event_crearPerroActionPerformed

    public void cicloLista() {
        DefaultListModel model = new DefaultListModel();
        for (Perro p : objList) {
            int index = 0;
            String data = p.getCodigo() + " - " + p.getNombre();
            model.add(index, data);
            index++;
        }
        listasMascotas.setModel(model);
    }

    public void clear() {
        nomPerro.setText("");
        codPerro.setText("");
        colorPerro.setText("");
        saludPerro.setSelectedIndex(0);
        razaPerro.setSelectedIndex(0);
        nacPerro.setText("");
        peligriPerro.setSelected(false);

    }
    private void buscarPerroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPerroActionPerformed
        
        String codigo = codPerro.getText();
        
        boolean opc = false;
        
        for(Perro perro: objList){
            if(perro.getCodigo().equals(codigo)){
                nomPerro.setText(perro.getNombre());
                colorPerro.setText(perro.getColor());
                nacPerro.setText(perro.getAnhioNac()+ "");
                razaPerro.setSelectedItem(perro.getRaza());
                saludPerro.setSelectedItem(perro.getEstadoSalud());
                peligriPerro.setSelected(perro.getPeligri());
                
                JOptionPane.showMessageDialog(this, "Datos encontrados");
                opc= true;
                break;  
            }
        }
        if(!opc ){
            JOptionPane.showMessageDialog(this, "El codigo no exite ");
            this.clear();
        }
        
    }//GEN-LAST:event_buscarPerroActionPerformed

    private void eliminarPerroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarPerroActionPerformed

        String codigo = codPerro.getText();
        boolean opc = false;//encontrar

        for (Perro p : objList) {
            if (p.getCodigo().equals(codigo)) {
                this.objList.remove(p);
                this.clear();
                this.cicloLista();
                JOptionPane.showMessageDialog(this, "se ha removido con exito");
                opc = true;
                break;
            }

        }
        if (!opc) {
            JOptionPane.showMessageDialog(this, "codigo " + codigo + " invalido");
        }


    }//GEN-LAST:event_eliminarPerroActionPerformed

    public void cicloListaGato() {
        DefaultListModel modelGato = new DefaultListModel();

        int index = 0;
        for (Gato gato : objListGato) {
            String data = gato.getCodigo() + " - " + gato.getNombre();
            modelGato.add(index, data);
            index++;
        }
        listaGatos.setModel(modelGato);

    }

    public void clearGato() {
        codGato.setText("");
        nomGato.setText("");
        colorGato.setText("");
        nacGato.setText("");
        razaGato.setSelectedIndex(0);
        saludGato.setSelectedIndex(0);

    }

    private void crearGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearGatoActionPerformed

        String codigo = codGato.getText();
        String nombre = nomGato.getText();
        String color = colorGato.getText();
        int anhioNac = Integer.parseInt(nacGato.getText());
        String raza = razaGato.getSelectedItem().toString();
        String estadoSalud = saludGato.getSelectedItem().toString();

        try {
            if (codigo.equals("") || nombre.equals("") || color.equals("")) {
                JOptionPane.showConfirmDialog(this, "hay campos vacios");

            } else {
                Gato gato1 = new Gato(raza, codigo, nombre, anhioNac, color, estadoSalud);
                objListGato.add(gato1);
                this.cicloListaGato();
                JOptionPane.showMessageDialog(this, "Creacion Exitosa");
                this.clearGato();

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Esta errado o vacio el campo añio nacimiento");
        }
    }//GEN-LAST:event_crearGatoActionPerformed

    private void eliminarGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarGatoActionPerformed

        String codigo = codGato.getText();
        boolean encontar = false;

        for (Gato gato : objListGato) {
            if (gato.getCodigo().equals(codigo)) {
                objListGato.remove(gato);
                this.cicloListaGato();
                JOptionPane.showMessageDialog(this, "Emininacion Exitosa");
                clearGato();
                encontar = true;
                break;
            }

        }
        if (encontar = false) {
            JOptionPane.showMessageDialog(this, "codigo " + codigo + " no encontrado");
        }


    }//GEN-LAST:event_eliminarGatoActionPerformed

    private void crearPajaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearPajaroActionPerformed

        try {
            String codigo = codPajaro.getText();
            String nombre = nomPajaro.getText();
            String color = colorPajaro.getText();
            int anhioNac = Integer.parseInt(nacPajaro.getText());
            String raza = razPajaro.getSelectedItem().toString();
            String estadoSalud = saludPajaro.getSelectedItem().toString();

            if (codigo.equals("") || nombre.equals("") || color.equals("")) {
                JOptionPane.showMessageDialog(this, "Debe llenar todos campos");
            } else {
                Pajaro parajaro1 = new Pajaro(raza, codigo, nombre, anhioNac, color, estadoSalud);
                objeListPajaro.add(parajaro1);
                cicloListaPajaro();
                JOptionPane.showMessageDialog(this, "Creacion Exitosa");
                clearPajaro();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Dato incorecto en fecha de nacimiento");
        }
    }//GEN-LAST:event_crearPajaroActionPerformed

    private void eliminarPajaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarPajaroActionPerformed

        String codigo = codPajaro.getText();
        boolean encontar = false;

        for (Pajaro pajaro : objeListPajaro) {

            if (pajaro.getCodigo().equals(codigo)) {
                objeListPajaro.remove(pajaro);
                cicloListaPajaro();
                JOptionPane.showMessageDialog(this, "Eliminacion Exitosa");
                clearPajaro();
                encontar = true;
                break;
            }    
        }
        if (encontar== false){
            JOptionPane.showMessageDialog(this, "El codigo "+codigo+ " no ha sido encontrado");
        }
        
    }//GEN-LAST:event_eliminarPajaroActionPerformed

    private void editarPerroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarPerroActionPerformed
        
        String codigo = codPerro.getText();
        boolean opc = false;
        
        for(Perro perro: objList){
            if(perro.getCodigo().equals(codigo)){
                String nombre = nomPerro.getText();
                String color = colorPerro.getText();
                int anhioNac = Integer.parseInt( nacPerro.getText());
                String estadoSalud = saludPerro.getSelectedItem().toString();
                String raza = razaPerro.getSelectedItem().toString();
                boolean peligri = peligriPerro.isSelected();
                
                perro.setNombre(nombre);
                perro.setColor(color);
                perro.setAnhioNac(anhioNac);
                perro.setEstadoSalud(estadoSalud);
                perro.setRaza(raza);
                perro.setPeligri(peligri);
                
                this.cicloLista();
                JOptionPane.showMessageDialog(this, "Datos Actualizados");
                opc = true;
                break;
                       
            }
        }
        if(!opc){
            JOptionPane.showMessageDialog(this, "el codigo "+ codigo +" no existe");
            this.clear();
        }
    }//GEN-LAST:event_editarPerroActionPerformed

    private void nacPerroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacPerroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nacPerroActionPerformed

    private void buscarGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarGatoActionPerformed
        
        String codigo = codGato.getText();
        boolean opc = false;
        
        for(Gato gato: objListGato){
            if(gato.getCodigo().equals(codigo)){
                nomGato.setText(gato.getNombre());
                colorGato.setText(gato.getColor());
                nacGato.setText(gato.getAnhioNac()+ "");
                saludGato.setSelectedItem(gato.getEstadoSalud());
                razaGato.setSelectedItem(gato.getRaza());
                   
                JOptionPane.showMessageDialog(this, "Datos encontrados");
                opc= true;
                break;  
                
            }
        }
        if(!opc){
            JOptionPane.showMessageDialog(this, "El codigo "+ codigo+ " no encontrado ");
            this.clearGato();
        }
    }//GEN-LAST:event_buscarGatoActionPerformed

    private void editarGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarGatoActionPerformed
        
        String codigo = codGato.getText();
        boolean opc = false;
        
        for (Gato gato: objListGato){
           if (gato.getCodigo().equals(codigo)){
               String nombre = nomGato.getText();
               String color = colorGato.getText();
               int anhioNac = Integer.parseInt(nacGato.getText());
               String raza = razaGato.getSelectedItem().toString();
               String estadoSalud = saludGato.getSelectedItem().toString();
               
               gato.setNombre(nombre);
               gato.setColor(color);
               gato.setAnhioNac(anhioNac);
               gato.setEstadoSalud(estadoSalud);
               
               cicloListaGato();
               JOptionPane.showMessageDialog(this, "Actualizacion exitosa");
               clearGato();
               opc = true;
               break;
           }
        }
        if(!opc){
            JOptionPane.showMessageDialog(this, "el codigo "+ codigo+ " no encontrado");
        }
    }//GEN-LAST:event_editarGatoActionPerformed

    public void cicloListaPajaro() {
        DefaultListModel modelPajaro = new DefaultListModel();
        int index = 0;

        for (Pajaro pajaro : objeListPajaro) {
            String data = pajaro.getCodigo() + " - " + pajaro.getNombre();
            modelPajaro.add(index, data);
            index++;
        }
        listaPajaros.setModel(modelPajaro);

    }

    public void clearPajaro() {
        codPajaro.setText("");
        nomPajaro.setText("");
        colorPajaro.setText("");
        nacPajaro.setText("");
        razPajaro.setSelectedIndex(0);
        saludPajaro.setSelectedIndex(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistasMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistasMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistasMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistasMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistasMascotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarGato;
    private javax.swing.JButton buscarPajaro;
    private javax.swing.JButton buscarPerro;
    private javax.swing.JTextField codGato;
    private javax.swing.JTextField codPajaro;
    private javax.swing.JTextField codPerro;
    private javax.swing.JTextField colorGato;
    private javax.swing.JTextField colorPajaro;
    private javax.swing.JTextField colorPerro;
    private javax.swing.JButton crearGato;
    private javax.swing.JButton crearPajaro;
    private javax.swing.JButton crearPerro;
    private javax.swing.JButton editarGato;
    private javax.swing.JButton editarPajaro;
    private javax.swing.JButton editarPerro;
    private javax.swing.JButton eliminarGato;
    private javax.swing.JButton eliminarPajaro;
    private javax.swing.JButton eliminarPerro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> listaGatos;
    private javax.swing.JList<String> listaPajaros;
    private javax.swing.JList<String> listasMascotas;
    private javax.swing.JTextField nacGato;
    private javax.swing.JTextField nacPajaro;
    private javax.swing.JTextField nacPerro;
    private javax.swing.JTextField nomGato;
    private javax.swing.JTextField nomPajaro;
    private javax.swing.JTextField nomPerro;
    private javax.swing.JCheckBox peligriPerro;
    private javax.swing.JComboBox<String> razPajaro;
    private javax.swing.JComboBox<String> razaGato;
    private javax.swing.JComboBox<String> razaPerro;
    private javax.swing.JComboBox<String> saludGato;
    private javax.swing.JComboBox<String> saludPajaro;
    private javax.swing.JComboBox<String> saludPerro;
    private javax.swing.JLabel texFieldGato;
    // End of variables declaration//GEN-END:variables
}
