/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;
import javax.swing.JOptionPane;
import ClasesMascotas.*;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import controlador.*;
/**
 *
 * @author Esquivel_Cesar
 */
public class vsitamascotas extends javax.swing.JFrame {
    ctrolmascota ctlmascota;
    LinkedList<clsPerro> dogObjectList = new LinkedList<>();
    LinkedList<clsGato> gatObjectLis = new LinkedList<>();
    /**
     * Creates new form vsitamascotas
     */
    public vsitamascotas() {
        initComponents();
        this.ctlmascota = new ctrolmascota();
        this.dogObjectList = ctlmascota.ListarMascota("Perro");
        this.listasmascotas();
    }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        list = new javax.swing.JTabbedPane();
        listasmascotas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listpet = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtcodperro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnomperro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtanioperro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcolorperro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comesaludperro = new javax.swing.JComboBox<>();
        comrazaperro = new javax.swing.JComboBox<>();
        btncrearperro = new javax.swing.JButton();
        btnbuscarperro = new javax.swing.JButton();
        btneditarperro = new javax.swing.JButton();
        btneliminarperro = new javax.swing.JButton();
        checpedperro = new javax.swing.JCheckBox();
        limpiar = new javax.swing.JButton();
        txIdPerro = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txIDMascota = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtCodGato = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtNacGato = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtNomGato = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtColorGato = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        comBoxEstaSalGato = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        comBoxRazaGato = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        txtIdGato = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtIdMasG = new javax.swing.JTextField();
        btnCrearGato = new javax.swing.JButton();
        btnBuscarGato = new javax.swing.JButton();
        btnEditarGato = new javax.swing.JButton();
        btnEliminarGato = new javax.swing.JButton();
        limpiar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("ADMINISTRACION MASCOTAS");

        listpet.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Código     Nombre     Raza         Color" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listpet);

        jLabel8.setText("Código");

        jLabel9.setText("Nombre");

        jLabel10.setText("Raza");

        jLabel11.setText("Color");

        javax.swing.GroupLayout listasmascotasLayout = new javax.swing.GroupLayout(listasmascotas);
        listasmascotas.setLayout(listasmascotasLayout);
        listasmascotasLayout.setHorizontalGroup(
            listasmascotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listasmascotasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listasmascotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                    .addGroup(listasmascotasLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel8)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel9)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel10)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        listasmascotasLayout.setVerticalGroup(
            listasmascotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listasmascotasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listasmascotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        list.addTab("Listas", listasmascotas);

        jLabel2.setText("Codigo");

        jLabel3.setText("Nombre");

        jLabel4.setText("Año Nac");

        jLabel5.setText("Color");

        txtcolorperro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcolorperroActionPerformed(evt);
            }
        });

        jLabel6.setText("Estado Salud");

        jLabel7.setText("Raza");

        comesaludperro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saludable", "Enfermo" }));
        comesaludperro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comesaludperroActionPerformed(evt);
            }
        });

        comrazaperro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beagle", "Jack Russell", "Pastor Alemán", "Fox Terrier Toy", "Yorkshire Terrier", "Chihuahua", "Pastor Alemán" }));

        btncrearperro.setText("Crear");
        btncrearperro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearperroActionPerformed(evt);
            }
        });

        btnbuscarperro.setText("Buscar");
        btnbuscarperro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarperroActionPerformed(evt);
            }
        });

        btneditarperro.setText("Editar");
        btneditarperro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarperroActionPerformed(evt);
            }
        });

        btneliminarperro.setText("Eliminar");
        btneliminarperro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarperroActionPerformed(evt);
            }
        });

        checpedperro.setText("Pedigree");
        checpedperro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checpedperroActionPerformed(evt);
            }
        });

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        txIdPerro.setEnabled(false);
        txIdPerro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txIdPerroActionPerformed(evt);
            }
        });

        jLabel12.setText("ID Perro");

        jLabel13.setText("ID Macosta");

        txIDMascota.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtcodperro, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(txtanioperro)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comesaludperro, 0, 85, Short.MAX_VALUE)
                                    .addComponent(txIdPerro))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtnomperro)
                                    .addComponent(txtcolorperro, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                    .addComponent(comrazaperro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(32, 32, 32)
                                .addComponent(checpedperro))
                            .addComponent(txIDMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btncrearperro)
                        .addGap(18, 18, 18)
                        .addComponent(btnbuscarperro)
                        .addGap(18, 18, 18)
                        .addComponent(btneditarperro)
                        .addGap(18, 18, 18)
                        .addComponent(btneliminarperro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(limpiar)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcodperro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtnomperro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtanioperro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtcolorperro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(comesaludperro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comrazaperro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checpedperro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txIdPerro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txIDMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncrearperro)
                    .addComponent(btnbuscarperro)
                    .addComponent(btneditarperro)
                    .addComponent(btneliminarperro)
                    .addComponent(limpiar))
                .addGap(20, 20, 20))
        );

        list.addTab("Admin Perro", jPanel2);

        jLabel14.setText("Codigo");

        jLabel15.setText("Año Nac");

        jLabel16.setText("Nombre");

        jLabel17.setText("Color");

        txtColorGato.setToolTipText("");

        jLabel18.setText("Estado Salud");

        comBoxEstaSalGato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saludable", "Enfermo", "Cirugia" }));

        jLabel19.setText("Raza");

        comBoxRazaGato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Siames", "Bengala", "Persa" }));
        comBoxRazaGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBoxRazaGatoActionPerformed(evt);
            }
        });

        jLabel20.setText("ID Gato");

        txtIdGato.setEnabled(false);

        jLabel21.setText("ID Mascota");

        txtIdMasG.setEnabled(false);

        btnCrearGato.setText("Crear");
        btnCrearGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearGatoActionPerformed(evt);
            }
        });

        btnBuscarGato.setText("Buscar");
        btnBuscarGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarGatoActionPerformed(evt);
            }
        });

        btnEditarGato.setText("Editar");
        btnEditarGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarGatoActionPerformed(evt);
            }
        });

        btnEliminarGato.setText("Eliminar");
        btnEliminarGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarGatoActionPerformed(evt);
            }
        });

        limpiar2.setText("Limpiar");
        limpiar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCrearGato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarGato)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarGato)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarGato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limpiar2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNacGato, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(txtCodGato)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel20)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comBoxEstaSalGato, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtIdGato))))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel19))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNomGato)
                                    .addComponent(txtColorGato)
                                    .addComponent(comBoxRazaGato, 0, 78, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIdMasG)))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCodGato, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtNomGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtNacGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtColorGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comBoxEstaSalGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)
                        .addComponent(comBoxRazaGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtIdGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(txtIdMasG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearGato)
                    .addComponent(btnBuscarGato)
                    .addComponent(btnEditarGato)
                    .addComponent(btnEliminarGato)
                    .addComponent(limpiar2))
                .addGap(21, 21, 21))
        );

        list.addTab("Admin Gato", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(list)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(341, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(40, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcolorperroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcolorperroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcolorperroActionPerformed

    private void comesaludperroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comesaludperroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comesaludperroActionPerformed

    private void btncrearperroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearperroActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(this, "Presiono el botón Crear");

        try {
//            int idperro = Integer.parseInt(txIdPerro.getText());
//            String idMascota = txIdPerro.getText();
            String codPerro = txtcodperro.getText();
            String nomPerro = txtnomperro.getText();
            String colPerro = txtcolorperro.getText();
            int nacPerro = Integer.parseInt(txtanioperro.getText());
            String saludPerro = comesaludperro.getSelectedItem().toString();
            String razaPerro = comrazaperro.getSelectedItem().toString();
            boolean pedigPerro = checpedperro.isSelected();

            if( codPerro.equals("") || nomPerro.equals("") || colPerro.equals("")){
                JOptionPane.showMessageDialog(this, "Existen Campos Vacios");
            }
            else{
                clsPerro perro = new clsPerro(0, razaPerro, pedigPerro, 0, codPerro, nomPerro, nacPerro, colPerro, saludPerro);
                ctlmascota.CrearMascota(perro);
                dogObjectList.add(perro);
                this.listasmascotas(perro);
                JOptionPane.showMessageDialog(this, "Datos ingresados con Exito");
                this.borrarcampos();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor escrba la edad del perro");
        }

    }//GEN-LAST:event_btncrearperroActionPerformed

    private void btnbuscarperroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarperroActionPerformed
        // TODO add your handling code here:
                        
        String codigo = txtcodperro.getText();
        clsPerro perro = (clsPerro)ctlmascota.BuscarMascota(codigo, "Perro");
        
        if(perro == null){
            JOptionPane.showMessageDialog(this, "codigo no existe");
            
        }
        
        else{
                txIdPerro.setText(perro.getId()+"");
                txIDMascota.setText(perro.getId()+ "");
                txtnomperro.setText(perro.getNombre());
                txtcolorperro.setText(perro.getColor());
                txtanioperro.setText(perro.getAnioNac()+ "");
                comesaludperro.setSelectedItem(perro.getEstadoSalud());
                comrazaperro.setSelectedItem(perro.getRaza());
                checpedperro.setSelected(perro.getPedigree());
        }

//        String code = txtcodperro.getText();
//        boolean opc = false;
//        for (clsPerro perro : dogObjectList) {
//
//            if (perro.getCodigo().equals(code)) {
//                txtnomperro.setText(perro.getNombre());
//                txtcolorperro.setText(perro.getColor());
//                txtanioperro.setText(perro.getAnioNac()+ "");
//                comesaludperro.setSelectedItem(perro.getEstadoSalud());
//                comrazaperro.setSelectedItem(perro.getRaza());
//                checpedperro.setSelected(perro.getPedigree());
//
//                JOptionPane.showMessageDialog(this, "Datos Encontrados");
//                opc = true;
//                break;
//            }
//        }
//        if (!opc) {
//            JOptionPane.showMessageDialog(this, "Codigo no Existe");
//        }        // TODO add your handling code here:

    }//GEN-LAST:event_btnbuscarperroActionPerformed

    private void btneditarperroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarperroActionPerformed
        // TODO add your handling code here:
        
        String code = txtcodperro.getText();
        String nom = txtnomperro.getText();
        String col = txtcolorperro.getText();
        int nac = Integer.parseInt(txtanioperro.getText());
        String salud = comesaludperro.getSelectedItem().toString();
        String raza = comrazaperro.getSelectedItem().toString();
        boolean pedig = checpedperro.isSelected();
        
        //recibimos los id ya creados 
        try {
            int idperro = Integer.parseInt(txIdPerro.getText());
            int idmascota =  Integer.parseInt(txIDMascota.getText());
            
            //instanciamos el constructor 
            clsPerro perro =  new clsPerro(idperro, raza, pedig, idmascota, code, nom, nac, col, salud);
            
            boolean respuesta =  ctlmascota.EditarMascota(perro);
            if(respuesta){
                JOptionPane.showMessageDialog(this, "Edision exitosa");
                this.borrarcampos();
            }
            else {
                JOptionPane.showMessageDialog(this, "Error al actualizar");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Busque un codigo para ediarlo");
        }
        
        
//        String code = txtcodperro.getText();
//        boolean opc = false;
//        for (clsPerro perro : dogObjectList) {
//
//            if (perro.getCodigo().equals(code)) {
//                String nom = txtnomperro.getText();
//                String col = txtcolorperro.getText();
//                int nac = Integer.parseInt(txtanioperro.getText());
//                String salud = comesaludperro.getSelectedItem().toString();
//                String raza = comrazaperro.getSelectedItem().toString();
//                boolean pedig = checpedperro.isSelected();
//
//                perro.setNombre(nom);
//
//                perro.setColor(col);
//                perro.setEstadoSalud(salud);
//                perro.setAnioNac(nac);
//                perro.setRaza(raza);
//                perro.setPedigree(pedig);
//                JOptionPane.showMessageDialog(this, "Datos Actualizados");
//                this.listasmascotas(); //actulizamos la lista despues de modificar
//                opc = true;
//
//                break;
//            }
//        }
//        if (!opc) {
//            JOptionPane.showMessageDialog(this, "Codigo no Existe");
//        }        // TODO add your handling code here:

    }//GEN-LAST:event_btneditarperroActionPerformed

    private void btneliminarperroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarperroActionPerformed

        String code = txtcodperro.getText();
        String nombre  = txtnomperro.getText();
        String color  = txtcolorperro.getText();
        int nac = Integer.parseInt(txtanioperro.getText());
        String salud = comesaludperro.getSelectedItem().toString();
        String raza = comrazaperro.getSelectedItem().toString();
        boolean peligri = checpedperro.isSelected();
        
        try {
            int idPeroo = Integer.parseInt(txIdPerro.getText());
            int idMascota = Integer.parseInt(txIDMascota.getText());
            
            clsPerro perro = new clsPerro(idPeroo, raza, peligri , idMascota, code, nombre, nac, color, salud);
            boolean respuesta = ctlmascota.eliminarMascota(perro);
            if(respuesta){
                JOptionPane.showMessageDialog(this, "Resgistro Eliminado");
                this.borrarcampos();
            }else{
                JOptionPane.showMessageDialog(this, "Error al eliminar");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Busque un codigo que este registrado para eliminar");
        }   

//        String code = txtcodperro.getText();
//        boolean opc = false;
//        for (clsPerro perro : dogObjectList) {
//
//            if (perro.getCodigo().equals(code)) {
//                this.dogObjectList.remove(perro);
//                this.borrarcampos();
//                this.listasmascotas(perro);
//                JOptionPane.showMessageDialog(this, "Registro Borrado");
//                opc = true;
//                break;
//            }
//        }
//        if (!opc) {
//            JOptionPane.showMessageDialog(this, "Codigo no Existe");
//        }        // TODO add your handling code here:
    }//GEN-LAST:event_btneliminarperroActionPerformed

    private void checpedperroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checpedperroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checpedperroActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
        this.borrarcampos();
    }//GEN-LAST:event_limpiarActionPerformed

    private void txIdPerroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txIdPerroActionPerformed
  
    }//GEN-LAST:event_txIdPerroActionPerformed

    private void comBoxRazaGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBoxRazaGatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comBoxRazaGatoActionPerformed

    private void btnCrearGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearGatoActionPerformed
        // TODO add your handling code here:
        
        try {
            String codGato = txtCodGato.getText();
            String nomGato = txtNomGato.getText();
            String colGato = txtColorGato.getText();
            int nacGato = Integer.parseInt(txtNacGato.getText());
            String saludGato = comBoxEstaSalGato.getSelectedItem().toString();
            String razaGato = comBoxRazaGato.getSelectedItem().toString();

            if( codGato.equals("") || nomGato.equals("") || colGato.equals("")){
                JOptionPane.showMessageDialog(this, "Existen Campos Vacios");
            }
            else{
                clsGato gato = new clsGato(0, razaGato, 0, codGato, nomGato, nacGato, colGato, saludGato);
                ctlmascota.CrearMascota(gato);
                gatObjectList.add(gato);
                this.listasmascotas(gato);
                JOptionPane.showMessageDialog(this, "Datos ingresados con Exito");
                this.borrarcampos();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor escrba la edad del gato");
        }
    }//GEN-LAST:event_btnCrearGatoActionPerformed

    private void btnEditarGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarGatoActionPerformed
        // TODO add your handling code here:
        
        String code = txtCodGato.getText();
        String nom = txtNomGato.getText();
        String col = txtColorGato.getText();
        int nac = Integer.parseInt(txtNacGato.getText());
        String salud = comBoxEstaSalGato.getSelectedItem().toString();
        String raza = comBoxRazaGato.getSelectedItem().toString();
        
        
        //recibimos los id ya creados 
        try {
            int idgato = Integer.parseInt(txtIdGato.getText());
            int idmascotaGato =  Integer.parseInt(txtIdMasG.getText());
            
            //instanciamos el constructor 
            clsGato gato =  new clsGato(idgato, raza, idmascotaGato, code, nom, nac, col, salud);
            
            boolean respuesta =  ctlmascota.EditarMascota(gato);
            if(respuesta){
                JOptionPane.showMessageDialog(this, "Edision exitosa");
                this.borrarcampos();
            }
            else {
                JOptionPane.showMessageDialog(this, "Error al actualizar");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Busque un codigo para ediarlo");
        }
        
    }//GEN-LAST:event_btnEditarGatoActionPerformed

    private void btnBuscarGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarGatoActionPerformed
        // TODO add your handling code here:
        
        String codigo = txtCodGato.getText();
        clsGato gato = (clsGato)ctlmascota.BuscarMascota(codigo, "Gato");
        
        if(gato == null){
            JOptionPane.showMessageDialog(this, "codigo no existe");
            
        }
        
        else{
                txtIdGato.setText(gato.getId()+"");
                txtIdMasG.setText(gato.getId()+ "");
                txtNomGato.setText(gato.getNombre());
                txtColorGato.setText(gato.getColor());
                txtNacGato.setText(gato.getAnioNac()+ "");
                comBoxEstaSalGato.setSelectedItem(gato.getEstadoSalud());
                comBoxRazaGato.setSelectedItem(gato.getRaza());
                
                
        }
        
    }//GEN-LAST:event_btnBuscarGatoActionPerformed

    private void btnEliminarGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarGatoActionPerformed
        // TODO add your handling code here:
        String code = txtCodGato.getText();
        String nombre  = txtNomGato.getText();
        String color  = txtColorGato.getText();
        int nac = Integer.parseInt(txtNacGato.getText());
        String salud = comBoxEstaSalGato.getSelectedItem().toString();
        String raza = comBoxRazaGato.getSelectedItem().toString();
        
        try {
            int idGato = Integer.parseInt(txtIdGato.getText());
            int idMascota = Integer.parseInt(txtIdMasG.getText());
            
            clsGato gato =  new clsGato(idGato, raza, idMascota, code, nombre, nac, color, salud);
            boolean respuesta = ctlmascota.eliminarMascota(gato);
            if(respuesta){
                JOptionPane.showMessageDialog(this, "Resgistro Eliminado");
                this.borrarcampos();
            }else{
                JOptionPane.showMessageDialog(this, "Error al eliminar");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Busque un codigo que este registrado para eliminar");
        }   

    }//GEN-LAST:event_btnEliminarGatoActionPerformed

    private void limpiar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiar2ActionPerformed
        // TODO add your handling code here:
        this.borrarcampos();
    }//GEN-LAST:event_limpiar2ActionPerformed
 
// MOSTRAR LOS REGISTROS EN LA OPCION LISTA    
    private void listasmascotas() {
        DefaultListModel model = new DefaultListModel();
        int index = 0;
        for (mascota perro : dogObjectList){
            String data = perro.getCodigo() + "       -       " + perro.getNombre() + "       -     " + perro.getEstadoSalud()+ "       -      " + perro.getColor() + "     Tipo Perro";
            model.add(index, data);
            index++;
        }
        listpet.setModel(model);
        
    }   

    //metodo para borrar los campos    
    private void borrarcampos(){
        
        txIDMascota.setText("");
        txIdPerro.setText("");
        txtcodperro.setText("");
        txtnomperro.setText("");
        txtcolorperro.setText("");
        txtanioperro.setText("");
        comesaludperro.setSelectedIndex(0);
        comrazaperro.setSelectedIndex(0);
        checpedperro.setSelected(false);
        
        txtCodGato.setText("");
        txtIdGato.setText("");
        txtCodGato.setText("");
        txtNomGato.setText("");
        txtNacGato.setText("");
        txtColorGato.setText("");
        comBoxEstaSalGato.setSelectedItem(0);
        comBoxRazaGato.setSelectedItem(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vsitamascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vsitamascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vsitamascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vsitamascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vsitamascotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarGato;
    private javax.swing.JButton btnCrearGato;
    private javax.swing.JButton btnEditarGato;
    private javax.swing.JButton btnEliminarGato;
    private javax.swing.JButton btnbuscarperro;
    private javax.swing.JButton btncrearperro;
    private javax.swing.JButton btneditarperro;
    private javax.swing.JButton btneliminarperro;
    private javax.swing.JCheckBox checpedperro;
    private javax.swing.JComboBox<String> comBoxEstaSalGato;
    private javax.swing.JComboBox<String> comBoxRazaGato;
    private javax.swing.JComboBox<String> comesaludperro;
    private javax.swing.JComboBox<String> comrazaperro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton limpiar2;
    private javax.swing.JTabbedPane list;
    private javax.swing.JPanel listasmascotas;
    private javax.swing.JList<String> listpet;
    private javax.swing.JTextField txIDMascota;
    private javax.swing.JTextField txIdPerro;
    private javax.swing.JTextField txtCodGato;
    private javax.swing.JTextField txtColorGato;
    private javax.swing.JTextField txtIdGato;
    private javax.swing.JTextField txtIdMasG;
    private javax.swing.JTextField txtNacGato;
    private javax.swing.JTextField txtNomGato;
    private javax.swing.JTextField txtanioperro;
    private javax.swing.JTextField txtcodperro;
    private javax.swing.JTextField txtcolorperro;
    private javax.swing.JTextField txtnomperro;
    // End of variables declaration//GEN-END:variables
}
